# Generated by Django 6.0.2 on 2026-02-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('modalidade', models.CharField(choices=[('CAMINHADA', 'Caminhada'), ('CORRIDA', 'Corrida'), ('AMBOS', 'Ambos')], max_length=20)),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='PLANEJADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_total', models.TimeField()),
                ('data_atividade', models.DateField()),
                ('tipo_registro', models.CharField(choices=[('GPS', 'GPS'), ('MANUAL', 'Manual')], max_length=10)),
                ('foto_atividade_url', models.ImageField(upload_to='comprovantes/%Y/%m/%d/')),
                ('status_validacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('observacao_auditoria', models.TextField(blank=True, null=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_auditadas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BayeuxApp.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='MetaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('distancia_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cor_hex', models.CharField(default='#3498db', help_text='Ex: #FFD700', max_length=7)),
                ('icone_medalha', models.ImageField(blank=True, null=True, upload_to='medalhas/')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='BayeuxApp.etapa')),
            ],
            options={
                'ordering': ['distancia_objetivo'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro')], max_length=15)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('provedor_gps', models.CharField(choices=[('NENHUM', 'Nenhum'), ('STRAVA', 'Strava'), ('GARMIN', 'Garmin'), ('NIKE', 'Nike Run Club')], default='NENHUM', max_length=20)),
                ('termo_responsabilidade', models.BooleanField(default=False)),
                ('aceite_lgpd', models.BooleanField(default=False)),
                ('status_conta', models.CharField(default='ATIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BayeuxApp.bairro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConquistaMandala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BayeuxApp.metaconfig')),
            ],
            options={
                'unique_together': {('user', 'meta')},
            },
        ),
    ]
