# Generated by Django 6.0.2 on 2026-02-21 22:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'db_table': 'bairros',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('modalidade', models.CharField(choices=[('CAMINHADA', 'Caminhada'), ('CORRIDA', 'Corrida'), ('AMBOS', 'Ambos')], max_length=20)),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='PLANEJADO', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='etapas/%Y/%m/%d/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'etapas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_total', models.TimeField()),
                ('data_atividade', models.DateField()),
                ('tipo_registro', models.CharField(choices=[('GPS', 'GPS'), ('MANUAL', 'Manual')], max_length=10)),
                ('comprovante', models.ImageField(upload_to='comprovantes_atividades/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('status_validacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=15)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('observacao_auditoria', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_auditadas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='BayeuxApp.etapa')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividades',
                'ordering': ['-data_atividade'],
            },
        ),
        migrations.CreateModel(
            name='MetaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('distancia_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cor_hex', models.CharField(default='#3498db', help_text='Ex: #FFD700', max_length=7)),
                ('icone_medalha', models.ImageField(blank=True, null=True, upload_to='medalhas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='BayeuxApp.etapa')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'metas_config',
                'ordering': ['distancia_objetivo'],
                'unique_together': {('etapa', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro')], max_length=15)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido')])),
                ('telefone', models.CharField(max_length=20)),
                ('provedor_gps', models.CharField(choices=[('NENHUM', 'Nenhum'), ('STRAVA', 'Strava'), ('GARMIN', 'Garmin'), ('NIKE', 'Nike Run Club')], default='NENHUM', max_length=20)),
                ('termo_responsabilidade', models.BooleanField(default=False)),
                ('aceite_lgpd', models.BooleanField(default=False)),
                ('status_conta', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='BayeuxApp.bairro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='ValidacaoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante', models.FileField(upload_to='comprovantes_residencia/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=15)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencias_auditadas', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacao_residencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validação de Residência',
                'verbose_name_plural': 'Validações de Residência',
                'db_table': 'validacoes_residencia',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='ATIVA', max_length=15)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='BayeuxApp.etapa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricoes',
                'ordering': ['-data_inscricao'],
                'unique_together': {('user', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='ConquistaMandala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='BayeuxApp.metaconfig')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'db_table': 'conquistas_mandala',
                'ordering': ['-data_conquista'],
                'unique_together': {('user', 'meta')},
            },
        ),
    ]
