# Generated by Django 6.0.2 on 2026-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayeuxApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='etapa',
            name='ano_referencia',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='etapa',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='mes_referencia',
            field=models.IntegerField(default=1, help_text='1 para Janeiro, 2 para Fevereiro...'),
            preserve_default=False,
        ),
    ]
