# Generated by Django 6.0.2 on 2026-02-26 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayeuxApp', '0002_rename_name_etapa_nome_etapa_ano_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='comprovante_residencia',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_residencia/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BayeuxApp.bairro'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='status_conta',
            field=models.CharField(choices=[('PENDENTE_DADOS', 'Pendente de Dados'), ('AGUARDANDO_VALIDACAO', 'Aguardando Validação de Residência'), ('ATIVO', 'Ativo'), ('REJEITADO', 'Rejeitado'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE_DADOS', max_length=25),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
